---
title: Erik Collinder
subtitle: Designer
email: collinder.erik@gmail.com
phone: +49 157 92347590
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: /:collection/:path/
  uploads:
    title: Uploads
    output: true
