---
title: Erik Collinder
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:collection/:path/"
  uploads:
    title: Uploads
    output: true
subtitle: Designer
email: collinder.erik@gmail.com
phone: "+49 157 92347590"
skype: erik.collinder
linkedin: erikcollinder
sass:
  style: compressed
gems: [jekyll/imgix]
imgix:
  source: erikcollinder.imgix.net # Your imgix source address
  secure_url_token: FACEBEEF12 # (optional) The Secure URL Token associated with your source