---
title: Erik Collinder
subtitle: Designer
email: collinder.erik@gmail.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
